stages:
  - test-setup
  - deploy
  - clean

test:
  stage: test
  script:
    - make all
  allow_failure: false

deploy:
  stage: deploy
  script:
    - echo NOT IMPLEMENTED YET
  only:
    - master
  allow_failure: false

clean:
  when: always
  script:
    - make deepclean
  stage: clean
