stages:
  - test
  - deploy

test:
  stage: test
  script:
    - make all deepclean
  allow_failure: false

deploy:
  stage: deploy
  script:
    - echo NOT IMPLEMENTED YET
  only:
    - master
  allow_failure: false
