stages:
  - test
  - deploy

variables:
  JOB_NAME: "www-hanneseichblatt-de-test"

test-build:
  stage: test
  script:
    - make test || docker logs $JOB_NAME
  allow_failure: false

deploy-to-live:
  stage: deploy
  script:
    - docker-compose stop
    - docker-compose rm -f
    - docker-compose build --pull
    - docker-compose up -d
    - /usr/bin/test $(/usr/bin/docker ps | grep -c www-hanneseichblatt-de ) -ge 1
  only:
    - master
  allow_failure: false

clean:
  when: always
  script:
    - make clean
  stage: clean
