stages:
  - test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

before_script:
  - apk add make git py3-pip
  - pip3 install --break-system-packages pipenv
  - sed -i 's/docker run -ti/docker run -d/g' Makefile
  - git diff

test:
  stage: test
  image: docker
  services:
    - docker:dind
  variables:
    BASE_URL: "http://docker:1313"
  script:
    - git submodule update --init
    - pipenv install
    - pipenv run make serve test
  allow_failure: false

