stages:
  - test
  - deploy

variables:
  TEST_CONTAINER_NAME: "www-hanneseichblatt-de-test"
  TEST_IMAGE_NAME: "www-hanneseichblatt-de:test"

test-build:
  stage: test
  tags:
    - test
  script:
    - (docker images -a | grep $TEST_IMAGE_NAME ) && docker rmi -f $TEST_IMAGE_NAME
    - docker build -t www-hanneseichblatt-de:test .
    - (docker ps -a | grep $TEST_CONTAINER_NAME ) && docker rm -f $TEST_CONTAINER_NAME
    - docker run --detach --name $TEST_CONTAINER_NAME -t $TEST_IMAGE_NAME
    - sleep 2s
    - /usr/bin/test $(/usr/bin/docker ps | grep -c $TEST_IMAGE_NAME ) -ge 1
    - docker stop $TEST_CONTAINER_NAME
  allow_failure: false

deploy-to-live:
  stage: deploy
  tags:
    - live
  script:
    - docker-compose stop
    - docker-compose rm -f
    - docker-compose build --pull
    - docker-compose up -d
    - /usr/bin/test $(/usr/bin/docker ps | grep -c www-hanneseichblatt-de ) -ge 1
    - curl --silent -IL http://hanneseichblatt.de | grep HTTP\/ | tail -n1 | grep OK
  only:
    - master
  allow_failure: false
