stages:
  - deploy

deploy-to-test:
  stage: deploy
  tags:
    - test
  script:
    - docker-compose stop
    - docker-compose rm -f
    - docker-compose build --pull
    - docker-compose up -d
    - /usr/bin/test $(/usr/bin/docker ps | grep -c www-hanneseichblatt-de ) -ge 1
  except:
    - production
  allow_failure: false

deploy-to-live:
  stage: deploy
  tags:
    - live
  script:
    - docker-compose stop
    - docker-compose rm -f
    - docker-compose build --pull
    - docker-compose up -d
    - /usr/bin/test $(/usr/bin/docker ps | grep -c www-hanneseichblatt-de ) -ge 1
  only:
    - production
  allow_failure: false
