stages:
  - test
  - build

default:
  image: "${CI_TEMPLATE_REGISTRY_HOST}/pages/hugo:latest"

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production

test:
  script:
    - hugo --minify
  artifacts:
    paths:
      - public
    expire_in: 2 weeks
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: build
  image: "${CI_TEMPLATE_REGISTRY_HOST}/pages/hugo:latest"
  script:
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production