# Site settings
title: hanneseichblatt.de
#email: mail@hanneseichblatt.de
description: > # this means to ignore newlines until "baseurl:"
  hanneseichblatt.de
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.hanneseichblatt.de" # the base hostname & protocol for your site

title : hanneseichblatt.de
tagline: Personal Website
author :
  name : Hannes Eichblatt
  github : heichblatt
  twitter : heichblatt
  keybase: heichblatt

# Build settings
markdown: kramdown

exclude: [Dockerfile, Rakefile, Makefile, test, .gitlab-ci.yml, .git]
