baseURL = 'https://hanneseichblatt.de/'
languageCode = 'en-gb'
title = 'Hannes Eichblatt'
theme = 'minimal'

[taxonomies]
  tag = 'tags'

[params]
  description = 'Personal Website'
  author = 'Hannes Eichblatt'
  bio = 'DevOps Engineer'
  copyright = '&copy; 2023 Hannes Eichblatt'
  showPowerBy = false
  enableRSS = true
  customCSS = [ "css/custom.css" ]
  defaultContentLanguage = 'en'
  showToc = true

#[social]
#  github = 'heichblatt'
#  gitlab = 'heichblatt'
#  twitter = 'heichblatt'
#  mastodon = 'hachyderm.io/@heichblatt'